### ISSUE TITLE
[Trailing Column Info][Dangling HTML]

### ISSUE THREAD

**Issue by sara-02** [pycon-mentored-sprints/mentored-sprints-website#8]
In the [APAC timeline](https://mentored-sprint-for-diverse-beginners.readthedocs.io/04_agenda.html#id1l) Info there is a trailing column information:
`**:widths: 40 60 :header-row: 0**`
![Screenshot from 2020-05-15 14-24-40](https://user-images.githubusercontent.com/7047079/82031880-1ba26d80-96b8-11ea-99cd-54a5d3a0c38e.png)

**Comment by yspark90** [comment]
I'd like to work on this :)

**Comment by yspark90** [comment]
Sorry, forgot to mention the proposed changes for `04_agenda.rst`:

- Add `s` to table styling `:header-row: 0` under APAC section.
- Correct the indentation of APAC table contents (missing an indent for each "bullet")

**Comment by trallard** [comment]
Thanks @yspark90 please go ahead and make the proposed changes!

**Comment by yspark90** [comment]
PR with the changes: https://github.com/yspark90/mentored-sprints-website/pull/1
